{% set version = "1.0.4" %}

package:
  name: cc-plugin-glider
  version: {{ version }}

source:
  fn: cc-plugin-glider-{{ version }}.tar.gz
  url: https://github.com/ioos/cc-plugin-glider/archive/{{ version }}.tar.gz
  sha256: 013b4167972ca22755a32fb2bd898ebb2f32ba648d85014596f368950f2fc209

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - gliderdac = cc_plugin_glider.glider_dac:GliderCheck

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - compliance-checker >=1.0.0

test:
  imports:
    - cc_plugin_glider

about:
  home: https://github.com/ioos/cc-plugin-glider
  license: Apache 2.0
  summary: 'Compliance Checker Glider DAC plugin.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
