{% set version = "2.0.2" %}

package:
  name: cc-plugin-glider
  version: {{ version }}

source:
  url: https://github.com/ioos/cc-plugin-glider/archive/{{ version }}.tar.gz
  sha256: 16b0778d3427cba97b617854c5632f63f8ba3c8bb4d979da3f25d7628c10cfbb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gliderdac = cc_plugin_glider.glider_dac:GliderCheck

requirements:
  host:
    - python
    - pip
  run:
    - python
    - compliance-checker >=4.0.0

test:
  imports:
    - cc_plugin_glider
  commands:
    - compliance-checker --list-tests | grep -q gliderdac  # [not win]
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ioos/cc-plugin-glider
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Compliance Checker Glider DAC plugin

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
