{% set version = "1.0.6" %}

package:
  name: cc-plugin-glider
  version: {{ version }}

source:
  url: https://github.com/ioos/cc-plugin-glider/archive/{{ version }}.tar.gz
  sha256: f08810313efb11bf2ccf3696d2ef2cee36da211ab8bd1069ae13de5abe995330

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - gliderdac = cc_plugin_glider.glider_dac:GliderCheck

requirements:
  host:
    - python
    - pip
  run:
    - python
    - compliance-checker >=1.0.0

test:
  imports:
    - cc_plugin_glider

about:
  home: https://github.com/ioos/cc-plugin-glider
  license: Apache 2.0
  summary: 'Compliance Checker Glider DAC plugin.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
