{% set python_min = python_min|default("3.9") %}
{% set name = "cc-plugin-glider" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ioos/cc-plugin-glider/archive/v{{ version }}.tar.gz
  sha256: bbac17de8667626785b26d6163a111df849ad724675fcd660d8a5bace31cb108

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - gliderdac = cc_plugin_glider.glider_dac:GliderCheck

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - compliance-checker >=4.3.2

test:
  imports:
    - cc_plugin_glider
  commands:
    - compliance-checker --list-tests | grep -q gliderdac  # [not win]
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/ioos/cc-plugin-glider
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Compliance Checker Glider DAC plugin

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
