{% set version = "1.0.4" %}

package:
  name: cc-plugin-glider
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cc-plugin-glider/cc-plugin-glider-{{ version }}.tar.gz
  sha256: 19b847e151f858523e4f0fda087bc050efec3a5125e6d0d7f359572a001f4912

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - gliderdac = cc_plugin_glider.glider_dac:GliderCheck

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - compliance-checker >=1.0.0

test:
  imports:
    - cc_plugin_glider

about:
  home: https://github.com/ioos/cc-plugin-glider
  license: Apache 2.0
  summary: 'Compliance Checker Glider DAC plugin.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
