travis:
  secure:
    BINSTAR_TOKEN: T/vUbOIozHsGpCUxibhf6nvEBoLnNfv98Voxo9Hvq1iAEs3gf4JC0+V+JLUGRohRg9NSLLyEb3y18c0+v8noVDu3C4hHgfacLeKDWv+LC2Ky91YNfrW1UBoby8VJrm4S9o7grl6kOzzFxbxWom+SoS87jfjHnakv7f0OxGVjAk5Iwv7lxJQ4Un1MvMtogZnlRr6YeCd7QY+X9IDp4YGZWmEZWC1YEMSmLJnvyww93epyRYPZ3BGYWs8lIm3w4v/5Jyl2L/xgGNcZTXVxTgl4ayfx40Skvtd05xjxEksvLI2lgxr5wY5ekMXMN8K++A8ptZksZM20JbzBlwnsh/UUeLV66KFKUZNQqB8GNEeHO3eUXf1lJ+jENq6mXkIs/LgOQNuDLyVJJx98iPrgSwxFT43KEVQxPdvq07u3fjbj/Xp0cGeh19mA3lrtY+WJEvMDb6jOfcuOBDYXX2SKOzqcn9ywgxc4q4Tu92e26aJDOruh7Hkg7niHHJMl52g2LbOYuLXkbYZHB4M07DiCrxbQKCZXnAoO7QpyZqL+b12vv/qAzbhHsll2auWVrBQV0GI6eZ4UpxjaW9Ix9j7Rfw52E8NWr1Bi78aZ3N2P/fSvB3uo33XdeLnTETjo4MmsAB+oYXkHc142hnpPvSKV/x7XAT1Ih5ZNn8c6pds8YscEkjM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
