travis:
  secure:
    BINSTAR_TOKEN: X9jta37z+cQI5iSDRhUesJgx0cq+CC2xPJUbZFBNRE4i6xoNSIBENKIqpCd5MqBBUcrx4wthB1VR4+BQ7ZGS/fbpcE1AqR31RSKMpJcPn0JV2mn7pYKJiyqXCAll9aSxkvnlbruFNNP+tWsBpdM47QNqlTsBw8umQd+wk7yGd0IU24SQM1sEk7jDLoIf5y/OppM7OpE/fKfxH1aLCPjGNG8yEIolrhU7V67u3K1K2jlmi8n8GoaJWudi1+aO3I0TaOW5Qnu11tq4r5cPb1NlPr2dJ6z2rmZjo2Fht0k6Zl4ffjdz6PUNySAa6TvkKfMJ9hk4+BXFJom4J9LPNhjp5Q8WUL1cMltKwc1hFymD0WcBU2ZTptQI5jxvz6ngN5CdZHDK2Gz8foYNlxtJknQNw71FS1Wa6SJFG14Q/1f75PbrVm+/ERLAaZ3fq3tntfHKhN/ad+TzhlsJt2Wo3Y61/QBaSoKvlCmvTHAQB1eAi1kKyn2K+wbApTOhLghFttkmMCn99PROpzpgeYZelQ/MaZ2gyrrx8XVfcJdhe3myo3ZJKMUh0imornuNritwFRc4hc5UJQq50qg+vEdIgkg/sUx1YbNlgfr7amBa1qST6lqT/WfMjwi5vHD3K/SI5lXdJbPnMbFKnyt1oxTJhY95VF/t2TOs7MSXTL1BbAKZbYo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
